create or replace TABLE CUSTOMER_ADDRESS cluster by LINEAR(CA_ADDRESS_SK)(
	CA_ADDRESS_SK NUMBER(38,0) NOT NULL,
	CA_ADDRESS_ID VARCHAR(16) NOT NULL,
	CA_STREET_NUMBER VARCHAR(10),
	CA_STREET_NAME VARCHAR(60),
	CA_STREET_TYPE VARCHAR(15),
	CA_SUITE_NUMBER VARCHAR(10),
	CA_CITY VARCHAR(60),
	CA_COUNTY VARCHAR(30),
	CA_STATE VARCHAR(2),
	CA_ZIP VARCHAR(10),
	CA_COUNTRY VARCHAR(20),
	CA_GMT_OFFSET NUMBER(5,2),
	CA_LOCATION_TYPE VARCHAR(20)
);