create or replace TABLE MICROTECNICA_CATEGORIA (
	CATEGORIA VARCHAR(255),
	CATEGORIAID VARCHAR(20),
	IDENTIFICADOR_CATEGORIA VARCHAR(255),
	constraint MICROTECNICA_EQUIPAMENTO_UK1 unique (IDENTIFICADOR_CATEGORIA)
)COMMENT='Tabela com dados referentes a Categoria extra\u00EDda do MercadoGov'
;