create or replace TABLE TIME_DIM cluster by LINEAR(T_TIME_SK)(
	T_TIME_SK NUMBER(38,0) NOT NULL,
	T_TIME_ID VARCHAR(16) NOT NULL,
	T_TIME NUMBER(38,0),
	T_HOUR NUMBER(38,0),
	T_MINUTE NUMBER(38,0),
	T_SECOND NUMBER(38,0),
	T_AM_PM VARCHAR(2),
	T_SHIFT VARCHAR(20),
	T_SUB_SHIFT VARCHAR(20),
	T_MEAL_TIME VARCHAR(20)
);