create or replace TABLE CUSTOMER_DEMOGRAPHICS cluster by LINEAR(CD_DEMO_SK)(
	CD_DEMO_SK NUMBER(38,0) NOT NULL,
	CD_GENDER VARCHAR(1),
	CD_MARITAL_STATUS VARCHAR(1),
	CD_EDUCATION_STATUS VARCHAR(20),
	CD_PURCHASE_ESTIMATE NUMBER(38,0),
	CD_CREDIT_RATING VARCHAR(10),
	CD_DEP_COUNT NUMBER(38,0),
	CD_DEP_EMPLOYED_COUNT NUMBER(38,0),
	CD_DEP_COLLEGE_COUNT NUMBER(38,0)
);