create or replace TABLE HOUSEHOLD_DEMOGRAPHICS cluster by LINEAR(HD_DEMO_SK)(
	HD_DEMO_SK NUMBER(38,0) NOT NULL,
	HD_INCOME_BAND_SK NUMBER(38,0),
	HD_BUY_POTENTIAL VARCHAR(15),
	HD_DEP_COUNT NUMBER(38,0),
	HD_VEHICLE_COUNT NUMBER(38,0)
);