create or replace TABLE PARTSUPP (
	PS_PARTKEY NUMBER(38,0) NOT NULL,
	PS_SUPPKEY NUMBER(38,0) NOT NULL,
	PS_AVAILQTY NUMBER(38,0) NOT NULL,
	PS_SUPPLYCOST NUMBER(12,2) NOT NULL,
	PS_COMMENT VARCHAR(199)
);