create or replace TABLE TERMO_ADITIVO_CONTRATO_082014 (
	NUMERO_CONTRATO VARCHAR(20),
	CODIGO_ORGAO_SUPERIOR VARCHAR(20),
	NOME_ORGAO_SUPERIOR VARCHAR(200),
	CODIGO_ORGAO VARCHAR(20),
	NOME_ORGAO VARCHAR(200),
	CODIGO_UG VARCHAR(20),
	NOME_UG VARCHAR(200),
	NUMERO_TERMO_ADITIVO VARCHAR(20),
	DATA_PUBLICACAO VARCHAR(20),
	OBJETO VARCHAR(2000)
);