create or replace TABLE CATEGORIA_D (
	CATEGORIA_ID NUMBER(6,0),
	CATEGORIA VARCHAR(255),
	CATEGORIAID VARCHAR(20),
	IDENTIFICADOR_CATEGORIA VARCHAR(255),
	EMPRESA VARCHAR(255),
	constraint CATEGORIA_D_PK primary key (CATEGORIA_ID)
);