create or replace TABLE FABRICANTE_D (
	FABRICANTE_ID NUMBER(18,0),
	FABRICANTE VARCHAR(80),
	FABRICANTEID VARCHAR(20),
	IDENTIFICADOR_FABRICANTE VARCHAR(80),
	FABRICANTE2 VARCHAR(80),
	VALOR_LICITADO_ANO_ATUAL FLOAT,
	VALOR_LICITADO_ANO_ANTERIOR FLOAT,
	DATA_CARGA_COMPRASNET VARCHAR(500),
	RISCO_DUPLICIDADE_NOME VARCHAR(1),
	FABRICANTE_DO_MERCADOGOV VARCHAR(1),
	SEGMENTO_MERCADO VARCHAR(40),
	DATA_CARGA_DW TIMESTAMP_NTZ(6)
);